sudo: false

os:
- linux
- osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
  - os: osx
    compiler: gcc

env:
  matrix:
  - LIBXSMM_JIT=0
  - LIBXSMM_JIT=1

language: cpp

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

before_install:
  - pip install --user codecov

after_success:
  - eval ${CODECOV}

script:
  - source .env

  - if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    cd ${TRAVIS_BUILD_DIR} && make -e clean && make -e TRACE=1 ECFLAGS="-DREAL_TYPE=float ${ECFLAGS}" tests &&
    if [[ "${CXX}" != "g++" && "${TRAVIS_OS_NAME}" != "osx" ]]; then
      env LIBXSMM_TRACE=1 ${TRAVIS_BUILD_DIR}/tests/threadsafety 2> threadsafety-trace-${COVID}.txt; 
    fi &&
    eval ${RUNGCOV}

  - if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    cd ${TRAVIS_BUILD_DIR} && make -e clean && make -e TRACE=1 ECFLAGS="-DREAL_TYPE=double ${ECFLAGS}" tests &&
    if [[ "${CXX}" != "g++" && "${TRAVIS_OS_NAME}" != "osx" ]]; then
      env LIBXSMM_TRACE=1 ${TRAVIS_BUILD_DIR}/tests/threadsafety 2> threadsafety-trace-${COVID}.txt; 
    fi &&
    eval ${RUNGCOV}

  - if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    cd ${TRAVIS_BUILD_DIR} && make -e clean && ./make.sh -ci-rm -j &&
    ./make.sh -ci-rm test-cp2k &&
    ./make.sh -ci-rm test-smm &&
    eval ${RUNGCOV}

  - if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    cd ${TRAVIS_BUILD_DIR} && make -e clean && ./make.sh -ci-cm -j &&
    ./make.sh -ci-cm test-cp2k &&
    ./make.sh -ci-cm test-smm &&
    eval ${RUNGCOV}

  - if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    cd ${TRAVIS_BUILD_DIR} && make -e clean && ./make.sh -ci-cm -j STATIC=0 &&
    ./make.sh -ci-cm test-cp2k &&
    ./make.sh -ci-cm tests &&
    eval ${RUNGCOV}

  - if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    cd ${TRAVIS_BUILD_DIR} && make -e clean && ./make.sh -ci-cm -j SSE=0 AVX=0 &&
    ./make.sh -ci-cm test-smm &&
    eval ${RUNGCOV}

  - if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    cd ${TRAVIS_BUILD_DIR} && make -e clean && ./make.sh -ci-nek -j &&
    ./make.sh -ci-nek test-nek &&
    eval ${RUNGCOV}

