sudo: false

os:
- linux
- osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
  - os: osx
    compiler: gcc

env:
  - LIBXSMM_JIT=0
  - LIBXSMM_JIT=1

language: cpp

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
  artifacts: true
    s3_region: "us-east-1"
    paths:
    - $(rm -f artifacts.tar ; git ls-files -o | xargs tar rf artifacts.tar -T - ; echo artifacts.tar)

before_install:
  - pip install --user codecov

after_success:
  - eval ${CODECOV}

script:
  - cd ${TRAVIS_BUILD_DIR} &&
    if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    make -e clean && make -e TRACE=1 &&
    cd ${TRAVIS_BUILD_DIR}/tests &&
    make ECFLAGS="-DREAL_TYPE=float ${ECFLAGS}" TRACE=1 test &&
    if [[ "${CXX}" != "g++" && "${TRAVIS_OS_NAME}" != "osx" ]]; then env LIBXSMM_TRACE=1 ./threadsafety 2> threadsafety-trace-${COVID}.txt; fi &&
    eval ${RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    make -e clean && make -e TRACE=1 &&
    cd ${TRAVIS_BUILD_DIR}/tests &&
    make ECFLAGS="-DREAL_TYPE=double ${ECFLAGS}" TRACE=1 test &&
    if [[ "${CXX}" != "g++" && "${TRAVIS_OS_NAME}" != "osx" ]]; then env LIBXSMM_TRACE=1 ./threadsafety 2> threadsafety-trace-${COVID}.txt; fi &&
    eval ${RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    make -e clean &&
    ./make.sh -ci-cm -j test-cp2k &&
    eval ${RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    make -e clean &&
    ./make.sh -ci-cm -j STATIC=0 test-cp2k &&
    eval ${RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    make -e clean &&
    ./make.sh -ci-rm -j ECXXFLAGS="-DREAL_TYPE=float ${ECXXFLAGS}" test-cp2k &&
    eval ${RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    make -e clean &&
    ./make.sh -ci-cm -j test-smm &&
    eval ${RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    make -e clean &&
    ./make.sh -ci-cm -j SSE=0 test-smm &&
    eval ${RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    make -e clean &&
    ./make.sh -ci-cm -j SSE=0 AVX=0 test-smm &&
    eval ${RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    if [[ "${CXX}" == "g++" ]]; then source .codecov; fi &&
    make -e clean &&
    ./make.sh -ci-nek -j test-nek &&
    eval ${RUNGCOV}

