language: cpp

sudo: false

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

before_install:
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

compiler:
  - clang
  - gcc

script:
  - source .coverage &&
    make -e clean &&
    bash make.sh -ci-cm -j test-cp2k &&
    bash samples/cp2k/cp2k-test.sh &&
    ${LIBXSMM_COVERAGE}

  - source .coverage &&
    make -e clean &&
    bash make.sh -ci-rm -j test-smm &&
    bash samples/smm/smm-test.sh &&
    ${LIBXSMM_COVERAGE}

  - source .coverage &&
    make -e clean &&
    bash make.sh -ci-nek -j test-nek &&
    bash samples/nek/nek-test.sh &&
    ${LIBXSMM_COVERAGE}

