language: cpp

addons:
  apt:
    packages: 
    - gfortran
    - libblas-dev
    - liblapack-dev

compiler:
  - clang
  - gcc

script: 
 - make -e realclean
 - bash make.sh -cp2k -j
 - make -e cp2k
 - make -e test
 - bash test.sh
