language: cpp

sudo: false

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

before_install:
  - pip install --user codecov

after_success:
  - source .codecov && ${LIBXSMM_CODECOV}

compiler:
  - clang
  - gcc

script:
  - source .codecov &&
    make -e clean &&
    bash make.sh -ci-cm -j test-cp2k &&
    bash samples/cp2k/cp2k-test.sh &&
    echo ${LIBXSMM_RUNGCOV} &&
    bash ${LIBXSMM_RUNGCOV}

  - source .codecov &&
    make -e clean &&
    bash make.sh -ci-rm -j test-smm &&
    bash samples/smm/smm-test.sh &&
    echo ${LIBXSMM_RUNGCOV} &&
    bash ${LIBXSMM_RUNGCOV}

  - source .codecov &&
    make -e clean &&
    bash make.sh -ci-nek -j test-nek &&
    bash samples/nek/nek-test.sh &&
    echo ${LIBXSMM_RUNGCOV} &&
    bash ${LIBXSMM_RUNGCOV}

