language: cpp

sudo: false

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

before_install:
  - pip install --user codecov

after_success:
  - source .codecov && 
    eval ${LIBXSMM_RUNGCOV} &&
    eval ${LIBXSMM_CODECOV}

compiler:
  - clang
  - gcc

env:
  - LIBXSMM_JIT=0
  - LIBXSMM_JIT=1

script:
  - source .codecov &&
    make -e clean &&
    bash make.sh -ci-cm -j test-cp2k &&
    bash samples/cp2k/cp2k-test.sh

  - source .codecov &&
    make -e clean &&
    env ECFLAGS="-DREAL_TYPE=float ${ECFLAGS}" bash make.sh -ci-rm -j test-smm &&
    bash samples/smm/smm-test.sh

  - source .codecov &&
    make -e clean &&
    bash make.sh -ci-nek -j test-nek &&
    bash samples/nek/nek-test.sh

