language: cpp

sudo: false

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

before_install:
  - pip install --user codecov

after_success:
  - source .codecov && 
    eval ${LIBXSMM_RUNGCOV} &&
    eval ${LIBXSMM_CODECOV}

compiler:
  - clang
  - gcc

env:
  - LIBXSMM_JIT=0
  - LIBXSMM_JIT=1

script:
  - source .codecov &&
    make -e clean &&
    make ECFLAGS=-DREAL_TYPE=float test

  - source .codecov &&
    make -e clean &&
    make test

  - source .codecov &&
    make -e clean &&
    bash make.sh -ci-cm -j test-cp2k

  - source .codecov &&
    make -e clean &&
    bash make.sh -ci-cm -j test-smm

  - source .codecov &&
    make -e clean &&
    bash make.sh -ci-nek -j test-nek

