language: cpp

addons:
  apt:
    packages: 
    - gfortran
    - libblas-dev
    - liblapack-dev

compiler:
  - clang
  - gcc

script: 
 - make realclean
 - bash make.sh -cp2k -j
 - make samples
 - make test
 - bash test.sh
