language: cpp

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

compiler:
  - clang
  - gcc

script:
  - make -e realclean &&
    bash make.sh -ci-cm -j &&
    make -e samples &&
    make -e test &&
    bash samples/cp2k/cp2k-test.sh

  - true || (make -e realclean &&
    bash make.sh -ci-rm -j &&
    make -e samples &&
    make -e testf &&
    bash samples/smm/smm-test.sh)

  - make -e realclean &&
    make -e PEDANTIC=1 ALIGNED_STORES=1 JIT=1 &&
    rm -f samples/cp2k/cp2k-perf.sh &&
    bash make.sh -ci drytest &&
    bash samples/cp2k/cp2k-perf.sh &&
    bash samples/cp2k/cp2k-test.sh

  - make -e realclean &&
    make -e PEDANTIC=1 JIT=1 &&
    rm -f samples/smm/smmf-perf.sh &&
    bash make.sh -ci drytest &&
    bash samples/smm/smmf-perf.sh &&
    bash samples/smm/smm-test.sh

  - make -e realclean &&
    make -e PEDANTIC=1 JIT=1 BETA=0 &&
    rm -f samples/nek/stpm-perf.sh &&
    rm -f samples/nek/axhm-perf.sh &&
    rm -f samples/nek/rstr-perf.sh &&
    bash make.sh -cinek drytest &&
    make -e samples &&
    bash samples/nek/stpm-perf.sh &&
    bash samples/nek/axhm-perf.sh &&
    bash samples/nek/rstr-perf.sh &&
    bash samples/nek/nek-test.sh

