language: C

before_install: 
- sudo apt-get update -qq
 - sudo apt-get install -y liblapack-dev
 - sudo apt-get install -y build-essentials
 - sudo apt-get install -y gfortran 

script: 
 - make MNK="2 3, 23" test
 - grep "diff" samples/cp2k/cp2k-perf.txt | grep -v "diff=0.000" 
