language: cpp

addons:
  apt:
    packages: 
    - gfortran
    - libblas-dev
    - liblapack-dev

compiler:
  - clang
  - gcc

script: 
 - make -e realclean
 - bash make.sh -cia -j
 - make -e samples
 - make -e test
 - cd samples/cp2k
 - bash test.sh
 - cd ../..

 - make -e realclean
 - bash make.sh -cib -j
 - make -e samples
 - make -e test
 - cd samples/cp2k
 - bash test.sh
 - cd ../..

 - cd samples/nek
 - make -e stpm
 - make -e rstr
 - make -e axhm
