language: cpp

sudo: false

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

before_install:
  - pip install --user codecov

after_success:
  - codecov

compiler:
  - clang
  - gcc

script:
  - if [ "${CXX}" == "g++" ]; then export EFLAGS="--coverage" ELDFLAGS="--coverage" ; fi &&
    make -e realclean &&
    bash make.sh -ci-cm -j test-cp2k &&
    bash samples/cp2k/cp2k-test.sh

  - if [ "${CXX}" == "g++" ]; then export EFLAGS="--coverage" ELDFLAGS="--coverage" ; fi &&
    make -e realclean &&
    bash make.sh -ci-rm -j test-smm &&
    bash samples/smm/smm-test.sh

  - if [ "${CXX}" == "g++" ]; then export EFLAGS="--coverage" ELDFLAGS="--coverage" ; fi &&
    make -e realclean &&
    bash make.sh -ci-nek -j test-nek &&
    bash samples/nek/nek-test.sh

