language: cpp

sudo: false

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

before_install:
  - pip install --user codecov

after_success:
  - source .codecov && 
    eval ${LIBXSMM_CODECOV}

compiler:
  - clang
  - gcc

env:
  - LIBXSMM_JIT=0
  - LIBXSMM_JIT=1

script:
  - cd ${TRAVIS_BUILD_DIR} &&
    source .codecov &&
    make -e clean && make -e TRACE=1 &&
    cd ${TRAVIS_BUILD_DIR}/tests &&
    make ECFLAGS="-DREAL_TYPE=float ${ECFLAGS}" TRACE=1 test &&
    if [[ "${CXX}" != "g++" ]]; then env LIBXSMM_TRACE=1 ./threadsafety 2> /dev/null ; fi &&
    eval ${LIBXSMM_RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    source .codecov &&
    make -e clean && make -e TRACE=1 &&
    cd ${TRAVIS_BUILD_DIR}/tests &&
    make ECFLAGS="-DREAL_TYPE=double ${ECFLAGS}" TRACE=1 test &&
    if [[ "${CXX}" != "g++" ]]; then env LIBXSMM_TRACE=1 ./threadsafety 2> /dev/null ; fi &&
    eval ${LIBXSMM_RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    source .codecov &&
    make -e clean &&
    ./make.sh -ci-cm -j test-cp2k &&
    eval ${LIBXSMM_RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    source .codecov &&
    make -e clean &&
    ./make.sh -ci-cm -j STATIC=0 test-cp2k &&
    eval ${LIBXSMM_RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    source .codecov &&
    make -e clean &&
    ./make.sh -ci-rm -j ECXXFLAGS="-DREAL_TYPE=float ${ECXXFLAGS}" test-cp2k &&
    eval ${LIBXSMM_RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    source .codecov &&
    make -e clean &&
    ./make.sh -ci-cm -j test-smm &&
    eval ${LIBXSMM_RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    source .codecov &&
    make -e clean &&
    ./make.sh -ci-cm -j SSE=0 test-smm &&
    eval ${LIBXSMM_RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    source .codecov &&
    make -e clean &&
    ./make.sh -ci-cm -j SSE=0 AVX=0 test-smm &&
    eval ${LIBXSMM_RUNGCOV}

  - cd ${TRAVIS_BUILD_DIR} &&
    source .codecov &&
    make -e clean &&
    ./make.sh -ci-nek -j test-nek &&
    eval ${LIBXSMM_RUNGCOV}

